import brandRouter from './modules/brand/brand.routes.js'
import categoryRouter from './modules/category/category.routes.js'
import subcategoryRouter from './modules/subcategory/subcategory.routes.js'
import productRouter from './modules/product/product.routes.js'
import authRouter from './modules/auth/auth.routes.js'
import reviewRouter from './modules/review/review.routes.js'
import wishlistRouter from './modules/wishlist/wishlist.routes.js'
import cartRouter from './modules/cart/cart.routes.js'
import couponRouter from './modules/coupon/coupon.routes.js'
import orderRouter from './modules/order/order.routes.js'
import userRouter from './modules/user/user.routes.js'
export { userRouter,orderRouter ,couponRouter ,cartRouter,brandRouter, wishlistRouter ,categoryRouter,subcategoryRouter,productRouter,reviewRouter ,authRouter}